
2017-07-04 16:01:56,258 - root - INFO - Logger setup done, starting web server
2017-07-04 16:01:56,258 - CANServer - INFO - Logger Added
2017-07-04 16:02:53,430 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:136> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 138, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 16:02:53,439 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:136> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 138, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 16:03:04,590 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:136> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 138, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 16:03:04,593 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:136> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 138, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 16:03:05,791 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:03:05,791 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:03:22,314 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:03:22,314 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:05:00,371 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:05:00,372 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:09:15,834 - root - INFO - Logger setup done, starting web server
2017-07-04 16:09:15,835 - CANServer - INFO - Logger Added
2017-07-04 16:09:19,037 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:09:19,038 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:12:31,769 - root - INFO - Logger setup done, starting web server
2017-07-04 16:12:31,770 - CANServer - INFO - Logger Added
2017-07-04 16:12:48,739 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:12:48,740 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:15:06,863 - root - INFO - Logger setup done, starting web server
2017-07-04 16:15:06,863 - CANServer - INFO - Logger Added
2017-07-04 16:15:16,715 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:15:16,716 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:16:14,629 - root - INFO - Logger setup done, starting web server
2017-07-04 16:16:14,629 - CANServer - INFO - Logger Added
2017-07-04 16:16:19,242 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:16:19,243 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:17:00,931 - root - INFO - Logger setup done, starting web server
2017-07-04 16:17:00,931 - CANServer - INFO - Logger Added
2017-07-04 16:17:04,459 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:17:04,460 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:17:18,473 - root - INFO - Logger setup done, starting web server
2017-07-04 16:17:18,474 - CANServer - INFO - Logger Added
2017-07-04 16:17:21,736 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:17:21,737 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:18:05,245 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:137> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 139, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 16:18:05,251 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:137> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 139, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 16:18:06,499 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:18:06,500 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:23:18,306 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:137> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 139, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 16:23:18,309 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:137> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 139, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 16:23:19,549 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:23:19,550 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:23:39,638 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:137> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 139, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 16:23:39,641 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:137> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 139, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 16:23:41,042 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:23:41,044 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:24:03,438 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:24:03,440 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:25:57,137 - root - INFO - Logger setup done, starting web server
2017-07-04 16:25:57,137 - CANServer - INFO - Logger Added
2017-07-04 16:26:02,566 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:26:02,567 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:28:50,796 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:137> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 139, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 16:28:50,802 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:137> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 139, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 16:28:52,055 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:28:52,056 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:40:27,478 - root - INFO - Logger setup done, starting web server
2017-07-04 16:40:27,478 - CANServer - INFO - Logger Added
2017-07-04 16:40:35,120 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:40:35,121 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:41:07,296 - root - INFO - Logger setup done, starting web server
2017-07-04 16:41:07,296 - CANServer - INFO - Logger Added
2017-07-04 16:41:10,795 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:41:10,795 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:42:44,780 - root - INFO - Logger setup done, starting web server
2017-07-04 16:42:44,781 - CANServer - INFO - Logger Added
2017-07-04 16:42:48,027 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:42:48,028 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:43:44,671 - root - INFO - Logger setup done, starting web server
2017-07-04 16:43:44,672 - CANServer - INFO - Logger Added
2017-07-04 16:43:48,124 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:43:48,125 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:44:23,467 - root - INFO - Logger setup done, starting web server
2017-07-04 16:44:23,468 - CANServer - INFO - Logger Added
2017-07-04 16:44:26,048 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:44:26,048 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:44:50,644 - root - INFO - Logger setup done, starting web server
2017-07-04 16:44:50,645 - CANServer - INFO - Logger Added
2017-07-04 16:44:54,735 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:44:54,736 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:45:40,056 - root - INFO - Logger setup done, starting web server
2017-07-04 16:45:40,057 - CANServer - INFO - Logger Added
2017-07-04 16:45:44,938 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:45:44,938 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:52:41,754 - root - INFO - Logger setup done, starting web server
2017-07-04 16:52:41,755 - CANServer - INFO - Logger Added
2017-07-04 16:52:53,926 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:52:53,927 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:53:20,116 - root - INFO - Logger setup done, starting web server
2017-07-04 16:53:20,117 - CANServer - INFO - Logger Added
2017-07-04 16:53:24,850 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:53:24,850 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:54:05,341 - root - INFO - Logger setup done, starting web server
2017-07-04 16:54:05,342 - CANServer - INFO - Logger Added
2017-07-04 16:54:08,550 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:54:08,551 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:54:35,165 - root - INFO - Logger setup done, starting web server
2017-07-04 16:54:35,165 - CANServer - INFO - Logger Added
2017-07-04 16:54:39,402 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:54:39,402 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:55:52,470 - root - INFO - Logger setup done, starting web server
2017-07-04 16:55:52,470 - CANServer - INFO - Logger Added
2017-07-04 16:55:55,642 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:55:55,643 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:57:15,688 - root - INFO - Logger setup done, starting web server
2017-07-04 16:57:15,688 - CANServer - INFO - Logger Added
2017-07-04 16:57:20,659 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:57:20,660 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 16:59:48,322 - root - INFO - Logger setup done, starting web server
2017-07-04 16:59:48,323 - CANServer - INFO - Logger Added
2017-07-04 16:59:53,636 - can.socketcan.native - INFO - Created a socket
2017-07-04 16:59:53,636 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 17:01:43,271 - root - INFO - Logger setup done, starting web server
2017-07-04 17:01:43,271 - CANServer - INFO - Logger Added
2017-07-04 17:01:45,358 - can.socketcan.native - INFO - Created a socket
2017-07-04 17:01:45,359 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 17:02:51,562 - root - INFO - Logger setup done, starting web server
2017-07-04 17:02:51,563 - CANServer - INFO - Logger Added
2017-07-04 17:02:55,369 - can.socketcan.native - INFO - Created a socket
2017-07-04 17:02:55,370 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 17:04:01,260 - root - INFO - Logger setup done, starting web server
2017-07-04 17:04:01,260 - CANServer - INFO - Logger Added
2017-07-04 17:04:05,529 - can.socketcan.native - INFO - Created a socket
2017-07-04 17:04:05,530 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 17:07:15,081 - root - INFO - Logger setup done, starting web server
2017-07-04 17:07:15,082 - CANServer - INFO - Logger Added
2017-07-04 17:07:18,630 - can.socketcan.native - INFO - Created a socket
2017-07-04 17:07:18,630 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 17:09:01,339 - root - INFO - Logger setup done, starting web server
2017-07-04 17:09:01,339 - CANServer - INFO - Logger Added
2017-07-04 17:09:05,422 - can.socketcan.native - INFO - Created a socket
2017-07-04 17:09:05,423 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 17:09:39,492 - root - INFO - Logger setup done, starting web server
2017-07-04 17:09:39,493 - CANServer - INFO - Logger Added
2017-07-04 17:09:42,645 - can.socketcan.native - INFO - Created a socket
2017-07-04 17:09:42,645 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 17:10:32,172 - root - INFO - Logger setup done, starting web server
2017-07-04 17:10:32,172 - CANServer - INFO - Logger Added
2017-07-04 17:10:35,346 - root - INFO - Logger setup done, starting web server
2017-07-04 17:10:35,346 - CANServer - INFO - Logger Added
2017-07-04 17:10:40,428 - can.socketcan.native - INFO - Created a socket
2017-07-04 17:10:40,428 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 17:13:23,541 - root - INFO - Logger setup done, starting web server
2017-07-04 17:13:23,542 - CANServer - INFO - Logger Added
2017-07-04 17:13:27,515 - can.socketcan.native - INFO - Created a socket
2017-07-04 17:13:27,516 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 17:14:09,448 - root - INFO - Logger setup done, starting web server
2017-07-04 17:14:09,449 - CANServer - INFO - Logger Added
2017-07-04 17:14:12,730 - can.socketcan.native - INFO - Created a socket
2017-07-04 17:14:12,730 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 17:14:37,901 - root - INFO - Logger setup done, starting web server
2017-07-04 17:14:37,901 - CANServer - INFO - Logger Added
2017-07-04 17:14:42,316 - can.socketcan.native - INFO - Created a socket
2017-07-04 17:14:42,317 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 17:17:21,137 - root - INFO - Logger setup done, starting web server
2017-07-04 17:17:21,138 - CANServer - INFO - Logger Added
2017-07-04 17:17:27,235 - can.socketcan.native - INFO - Created a socket
2017-07-04 17:17:27,235 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 17:25:04,801 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 137, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 17:25:04,808 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 137, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 17:25:05,959 - can.socketcan.native - INFO - Created a socket
2017-07-04 17:25:05,959 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 17:25:07,470 - can.socketcan.native - INFO - Created a socket
2017-07-04 17:25:07,471 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 17:25:19,418 - can.socketcan.native - INFO - Created a socket
2017-07-04 17:25:19,419 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 17:25:24,364 - root - INFO - Logger setup done, starting web server
2017-07-04 17:25:24,365 - CANServer - INFO - Logger Added
2017-07-04 17:25:29,441 - can.socketcan.native - INFO - Created a socket
2017-07-04 17:25:29,444 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 17:26:20,363 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.producer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:140> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 143, in producer_handler
    await websocket.send(message)
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 310, in send
    yield from self.ensure_open()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 394, in ensure_open
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 17:26:20,370 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.producer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:140> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 143, in producer_handler
    await websocket.send(message)
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 310, in send
    yield from self.ensure_open()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 394, in ensure_open
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 17:26:21,590 - can.socketcan.native - INFO - Created a socket
2017-07-04 17:26:21,591 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 17:26:23,764 - can.socketcan.native - INFO - Created a socket
2017-07-04 17:26:23,766 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 17:27:11,181 - root - INFO - Logger setup done, starting web server
2017-07-04 17:27:11,182 - CANServer - INFO - Logger Added
2017-07-04 17:27:14,650 - can.socketcan.native - INFO - Created a socket
2017-07-04 17:27:14,651 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 17:30:50,284 - root - INFO - Logger setup done, starting web server
2017-07-04 17:30:50,285 - CANServer - INFO - Logger Added
2017-07-04 17:30:52,848 - can.socketcan.native - INFO - Created a socket
2017-07-04 17:30:52,848 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 18:08:20,468 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 137, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 18:08:20,479 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 137, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 18:08:21,668 - can.socketcan.native - INFO - Created a socket
2017-07-04 18:08:21,669 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 18:15:55,613 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 137, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 18:15:55,620 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 137, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 18:15:55,625 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 137, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 18:15:56,939 - can.socketcan.native - INFO - Created a socket
2017-07-04 18:15:56,941 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 18:34:50,610 - root - INFO - Logger setup done, starting web server
2017-07-04 18:34:50,610 - CANServer - INFO - Logger Added
2017-07-04 18:36:11,939 - root - INFO - Logger setup done, starting web server
2017-07-04 18:36:11,942 - CANServer - INFO - Logger Added
2017-07-04 18:36:57,954 - can.socketcan.native - INFO - Created a socket
2017-07-04 18:36:57,955 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 18:37:18,064 - can.socketcan.native - INFO - Created a socket
2017-07-04 18:37:18,065 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 18:44:21,353 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 137, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 18:44:21,370 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 137, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 18:44:21,373 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 137, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 18:44:21,569 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=TypeError('string indices must be integers',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 138, in consumer_handler
    await self.consumer(message)
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 107, in consumer
    if self.nodeNo != co["node"] and self.nodeNo != 0:
TypeError: string indices must be integers
2017-07-04 18:44:27,936 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=TypeError('string indices must be integers',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 138, in consumer_handler
    await self.consumer(message)
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 107, in consumer
    if self.nodeNo != co["node"] and self.nodeNo != 0:
TypeError: string indices must be integers
2017-07-04 18:44:57,566 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.producer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:140> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 143, in producer_handler
    await websocket.send(message)
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 310, in send
    yield from self.ensure_open()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 394, in ensure_open
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 18:44:57,568 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.producer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:140> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 143, in producer_handler
    await websocket.send(message)
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 310, in send
    yield from self.ensure_open()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 394, in ensure_open
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 18:44:57,571 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.producer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:140> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 143, in producer_handler
    await websocket.send(message)
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 310, in send
    yield from self.ensure_open()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 394, in ensure_open
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 18:44:57,573 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 137, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 18:44:58,891 - can.socketcan.native - INFO - Created a socket
2017-07-04 18:44:58,892 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 18:45:00,664 - can.socketcan.native - INFO - Created a socket
2017-07-04 18:45:00,666 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 18:46:58,003 - root - INFO - Logger setup done, starting web server
2017-07-04 18:46:58,003 - CANServer - INFO - Logger Added
2017-07-04 18:47:01,884 - can.socketcan.native - INFO - Created a socket
2017-07-04 18:47:01,884 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 18:56:58,891 - root - INFO - Logger setup done, starting web server
2017-07-04 18:56:58,892 - CANServer - INFO - Logger Added
2017-07-04 18:57:17,135 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.producer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:140> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 143, in producer_handler
    await websocket.send(message)
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 310, in send
    yield from self.ensure_open()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 402, in ensure_open
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 18:57:17,141 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 137, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 18:57:17,145 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 137, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 18:57:17,148 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 137, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 18:57:18,258 - can.socketcan.native - INFO - Created a socket
2017-07-04 18:57:18,259 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 18:57:21,514 - can.socketcan.native - INFO - Created a socket
2017-07-04 18:57:21,515 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 19:16:20,610 - can.socketcan.native - INFO - Created a socket
2017-07-04 19:16:20,611 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 19:16:50,687 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 137, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 19:16:50,690 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 137, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 19:16:50,693 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 137, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 19:16:51,994 - can.socketcan.native - INFO - Created a socket
2017-07-04 19:16:51,995 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 19:18:11,206 - can.socketcan.native - INFO - Created a socket
2017-07-04 19:18:11,208 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 19:18:38,057 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.producer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:140> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 143, in producer_handler
    await websocket.send(message)
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 310, in send
    yield from self.ensure_open()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 394, in ensure_open
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 19:18:38,065 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 137, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 19:18:38,072 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 137, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 19:18:38,077 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:135> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 137, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 19:18:38,080 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.producer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:140> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 143, in producer_handler
    await websocket.send(message)
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 310, in send
    yield from self.ensure_open()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 394, in ensure_open
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 19:18:39,368 - can.socketcan.native - INFO - Created a socket
2017-07-04 19:18:39,369 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 19:39:14,366 - root - INFO - Logger setup done, starting web server
2017-07-04 19:39:14,368 - CANServer - INFO - Logger Added
2017-07-04 19:39:49,999 - can.socketcan.native - INFO - Created a socket
2017-07-04 19:39:50,000 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 19:40:40,005 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:144> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 146, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 19:40:40,013 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:144> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 146, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 19:40:40,016 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:144> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 146, in consumer_handler
    message = await websocket.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-07-04 19:40:41,258 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at /home/pi/CAN/CANServer/python/CANServer.py:144> exception=AttributeError("'NoneType' object has no attribute 'stop'",)>
Traceback (most recent call last):
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 147, in consumer_handler
    await self.consumer(message)
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 137, in consumer
    self.initNetwork()
  File "/home/pi/CAN/CANServer/python/CANServer.py", line 43, in initNetwork
    network.disconnect()
  File "/usr/local/lib/python3.6/site-packages/canopen/network.py", line 103, in disconnect
    self.notifier.stop()
AttributeError: 'NoneType' object has no attribute 'stop'
2017-07-04 19:49:37,554 - root - INFO - Logger setup done, starting web server
2017-07-04 19:49:37,554 - CANServer - INFO - Logger Added
2017-07-04 19:49:42,768 - can.socketcan.native - INFO - Created a socket
2017-07-04 19:49:42,769 - canopen.network - INFO - Connected to 'native socketcan channel'
2017-07-04 19:49:49,700 - can.socketcan.native - INFO - Created a socket
2017-07-04 19:49:49,701 - canopen.network - INFO - Connected to 'native socketcan channel'
